### PR TITLE
Add compatibility for Nim 0.20+

### PR DESCRIPTION
**Pull request by greenfork**

### CODE REVIEW

**Comment by SolitudeSF** [comment]
i would advise to put this in the function and call it, since top level globals hurt performance/prevent optimizations.

**Comment by greenfork** [comment]
@SolitudeSF thank you for your piece of advice, done!

**Comment by rexim** [comment]
@greenfork 

> Add compatibility for Nim 0.20+

So without these changes the code doesn't work on Nim 0.20+? Really?!

**Comment by SolitudeSF** [comment]
defer statement now restricted from being toplevel. defer rewrites the body into implicity `try...finally` statement, so i dont know what it even did on toplevel before. probably caused bugs and shit.

**Comment by greenfork** [comment]
It doesn't compile without these changes, yes

**Comment by rexim** [comment]
@SolitudeSF interesting! Thanks for the information!

@greenfork thanks for the contribution!

**Pull request merged**
